'use client'

import { Document, Page, Text, View, StyleSheet, PDFDownloadLink, Font } from '@react-pdf/renderer'
import { useState, useEffect } from 'react'
import { Button } from '@/components/ui/button'
import { Download } from 'lucide-react'

// You can register Arabic fonts here later, e.g., Cairo or Tajawal
// Font.register({ family: 'Cairo', src: '/fonts/Cairo-Regular.ttf' })

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 12, lineHeight: 1.6 },
  header: { fontSize: 24, marginBottom: 20, textAlign: 'center', fontWeight: 'bold' },
  section: { marginBottom: 15 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 8, backgroundColor: '#f3f4f6', padding: 5 },
  row: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5, borderBottom: '1 solid #eee', paddingBottom: 3 },
  label: { color: '#666' },
  value: { fontWeight: 'bold' },
  footer: { marginTop: 40, fontSize: 10, color: '#888', textAlign: 'center', borderTop: '1 solid #eee', paddingTop: 10 }
})

const ContractDocument = ({ formData, selectedService, finalTotal }: any) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.header}>Project Contract & Agreement</Text>
      
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>1. Project Details</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Project Name:</Text>
          <Text style={styles.value}>{formData.projectName || 'N/A'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Location:</Text>
          <Text style={styles.value}>{formData.city}, {formData.country}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Area (sqm):</Text>
          <Text style={styles.value}>{formData.area || 'N/A'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Design Style:</Text>
          <Text style={styles.value}>{formData.styles.join(', ') || 'N/A'}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>2. Service & Pricing</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Selected Service:</Text>
          <Text style={styles.value}>{selectedService?.name || 'N/A'}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Total Estimated Cost:</Text>
          <Text style={styles.value}>{finalTotal.toLocaleString()} SAR</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>3. Terms & Conditions</Text>
        <Text>1. The client agrees to the estimated cost and scope of work defined in this document.</Text>
        <Text>2. Any additional revisions beyond the agreed scope will incur extra charges.</Text>
        <Text>3. The estimated duration will commence upon the receipt of the initial deposit.</Text>
        <Text>4. All designs remain the intellectual property of Masar until full payment is received.</Text>
        <Text>5. The client is responsible for providing accurate site dimensions if site visit is not included.</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>4. Client Obligations</Text>
        <Text>- Provide necessary approvals in a timely manner.</Text>
        <Text>- Ensure site accessibility during the agreed working hours.</Text>
        <Text>- Make payments according to the agreed schedule.</Text>
      </View>

      <View style={styles.footer}>
        <Text>Generated by Masar System • This is a binding electronic agreement.</Text>
      </View>
    </Page>
  </Document>
)

export function ContractPDFLink({ formData, selectedService, finalTotal, onDownload }: any) {
  const [isClient, setIsClient] = useState(false)
  
  useEffect(() => {
    setIsClient(true)
  }, [])

  if (!isClient) return null

  return (
    <PDFDownloadLink
      document={<ContractDocument formData={formData} selectedService={selectedService} finalTotal={finalTotal} />}
      fileName={`Contract_${formData.projectName || 'Project'}.pdf`}
    >
      {({ blob, url, loading, error }) => (
        <div onClick={() => { if (!loading) onDownload() }}>
          <Button
            type="button"
            variant="outline"
            className="w-full border-gold text-gold hover:bg-gold hover:text-white"
            disabled={loading}
          >
            <Download className="w-4 h-4 mr-2" />
            {loading ? 'جاري تجهيز العقد...' : 'تحميل تفاصيل المشروع والعقد (PDF)'}
          </Button>
        </div>
      )}
    </PDFDownloadLink>
  )
}
